Repository GSG-G11/news-team-2, pull requests merged in 2022-02, with the labels that each got.

#7 File structure
  css/index.css
  css/single-new.css
  index.html
  js/main.js
  single-new.html
Labels: Awaiting Review

#8 Finish Editing File Structure
  img/logo.png
  single-new.html
Labels: Done

#11 create header for the single page[ details page ]
  css/single-new.css
  img/1.jpeg
  single-new.html
Labels: Awaiting Review

#12 Create nav bar
  css/all.min.css
  css/index.css
  index.html
  js/main.js
  webfonts/fa-brands-400.eot
  webfonts/fa-brands-400.svg
  webfonts/fa-brands-400.ttf
  webfonts/fa-brands-400.woff
  webfonts/fa-brands-400.woff2
  webfonts/fa-regular-400.eot
  webfonts/fa-regular-400.svg
  webfonts/fa-regular-400.ttf
  webfonts/fa-regular-400.woff
  webfonts/fa-regular-400.woff2
  webfonts/fa-solid-900.eot
  webfonts/fa-solid-900.svg
  webfonts/fa-solid-900.ttf
  webfonts/fa-solid-900.woff
  webfonts/fa-solid-900.woff2
Labels: Awaiting Review

#13 write code html for body and start style
  .idea/.gitignore
  .idea/codeStyles/codeStyleConfig.xml
  .idea/modules.xml
  .idea/news-team-2.iml
  .idea/saveactions_settings.xml
  .idea/vcs.xml
  css/single-new.css
  img/avatar.png
  img/based-on-like.png
  img/recommended-for-you.png
  img/sub-img-1.jpg
  img/sub-img-2.jpg
  single-new.html
Labels: Awaiting Review

#18 make the single page body content responsive R #17
  css/single-new.css
  single-new.html
Labels: Done

#20 create the related blog section
  .idea/.gitignore
  .idea/codeStyles/codeStyleConfig.xml
  .idea/modules.xml
  .idea/news-team-2.iml
  .idea/saveactions_settings.xml
  .idea/vcs.xml
  css/single-new.css
  img/Group 269.png
  img/Group 270.png
  img/Vector (1).png
  img/image 55.png
  img/image 62.png
  img/image 63.png
  img/image 66.png
  single-new.html
Labels: Awaiting Review, daft

#24 make the header and the related blog section responsive
  css/single-new.css
Labels: Done

#26 Create A Responsive media Query
  css/single-new.css
  single-new.html
Labels: Awaiting Review

#19 Create footer
  css/index.css
  img/footerLogo.png
  index.html
Labels: Awaiting Review

#29 Finish Editing Container Class
  css/index.css
  index.html
Labels: Awaiting Review

#27 update the readme file
  README.md
Labels: Awaiting Review

#34 add the navbar and footer to the single page
  css/single-new.css
  single-new.html
Labels: Done

#39 Categories sections
  css/index.css
  img/business1.jpg
  img/business2.jpg
  img/business3.jpg
  img/culture1.jpg
  img/culture2.jpg
  img/culture3.jpg
  img/politics1.jpg
  img/politics2.jpg
  img/politics3.jpg
  img/sports1.png
  img/sports2.jpg
  img/sports3.jpg
  img/travel1.jpg
  img/travel2.jpg
  img/travel3.jpg
  img/world1.jpg
  img/world2.jpg
  img/world3.jpg
  index.html
Labels: Awaiting Review

#38 Fix Bug Responsive Single Page
  css/single-new.css
  single-new.html
Labels: Done

#44 Fix link image In Single page
  css/single-new.css
  single-new.html
Labels: Done
